spring.jpa.hibernate.ddl-auto=update

# Database Configuration (use environment variables in production)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/quiz-app}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:1206}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=bXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjEyMzQ1Njc4OTA=
jwt.expiration=86400000
